// <auto-generated />
using System;
using GymApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260410135938_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymApp.Core.Entities.Attendance", b =>
                {
                    b.Property<int>("AttId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttId"));

                    b.Property<DateTime>("CheckInTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClCode")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("AttId");

                    b.HasIndex("ClCode");

                    b.ToTable("Attendances", (string)null);
                });

            modelBuilder.Entity("GymApp.Core.Entities.Client", b =>
                {
                    b.Property<string>("ClCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("ClAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ClBirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClCoachId")
                        .HasColumnType("character varying(5)");

                    b.Property<string>("ClFname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ClLname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ClMembershipId")
                        .HasColumnType("integer");

                    b.Property<string>("ClPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime>("ClRegisterDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("ClStatus")
                        .HasColumnType("boolean");

                    b.Property<string>("DietitianId")
                        .HasColumnType("character varying(5)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ClCode");

                    b.HasIndex("ClCoachId");

                    b.HasIndex("ClMembershipId");

                    b.HasIndex("DietitianId");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("GymApp.Core.Entities.ClientGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<decimal?>("CurrentValue")
                        .HasColumnType("numeric");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClientCode");

                    b.ToTable("ClientGoals", (string)null);
                });

            modelBuilder.Entity("GymApp.Core.Entities.ClientMembership", b =>
                {
                    b.Property<int>("CmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CmId"));

                    b.Property<string>("ClCode")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("CmId");

                    b.HasIndex("ClCode");

                    b.HasIndex("MemId");

                    b.ToTable("ClientMemberships", (string)null);
                });

            modelBuilder.Entity("GymApp.Core.Entities.Coach", b =>
                {
                    b.Property<string>("CoCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("CoAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CoBirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CoEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CoFname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CoHireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CoLname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CoPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("CoSpecialty")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("CoStatus")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CoCode");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Coaches", (string)null);
                });

            modelBuilder.Entity("GymApp.Core.Entities.DietPlan", b =>
                {
                    b.Property<int>("DietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DietId"));

                    b.Property<string>("ClCode")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<string>("DietDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("DietEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DietStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DietitianId")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("DietId");

                    b.HasIndex("ClCode");

                    b.HasIndex("DietitianId");

                    b.ToTable("DietPlans", (string)null);
                });

            modelBuilder.Entity("GymApp.Core.Entities.Dietitian", b =>
                {
                    b.Property<string>("DietCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("DietEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DietFname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DietLname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DietPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<bool>("DietStatus")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("DietCode");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Dietitians", (string)null);
                });

            modelBuilder.Entity("GymApp.Core.Entities.MembershipPlan", b =>
                {
                    b.Property<int>("MemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MemId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MemDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MemDurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("MemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("MemPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("MemStatus")
                        .HasColumnType("boolean");

                    b.HasKey("MemId");

                    b.ToTable("MembershipPlans", (string)null);
                });

            modelBuilder.Entity("GymApp.Core.Entities.Notification", b =>
                {
                    b.Property<int>("NotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("NotId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("GymApp.Core.Entities.Payment", b =>
                {
                    b.Property<int>("PayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PayId"));

                    b.Property<string>("ClCode")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PayAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("PayDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PayMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PayStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("PayId");

                    b.HasIndex("ClCode");

                    b.HasIndex("MemId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("GymApp.Core.Entities.ProgressEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BodyFatPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Chest")
                        .HasColumnType("numeric");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EntryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("Waist")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ProgressEntries", (string)null);
                });

            modelBuilder.Entity("GymApp.Core.Entities.Review", b =>
                {
                    b.Property<int>("RevId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RevId"));

                    b.Property<string>("ClCode")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<string>("CoCode")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer");

                    b.HasKey("RevId");

                    b.HasIndex("ClCode");

                    b.HasIndex("CoCode");

                    b.HasIndex("SessionId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("GymApp.Core.Entities.Session", b =>
                {
                    b.Property<int>("SesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SesId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("SesClCode")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<string>("SesCoCode")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("SesDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SesDescription")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SesDuration")
                        .HasColumnType("integer");

                    b.Property<string>("SesStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Scheduled");

                    b.Property<string>("SesType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("SesId");

                    b.HasIndex("SesClCode");

                    b.HasIndex("SesCoCode");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("GymApp.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("UserStatus")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GymApp.Core.Entities.WorkoutExercise", b =>
                {
                    b.Property<int>("WeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WeId"));

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<int>("WpId")
                        .HasColumnType("integer");

                    b.HasKey("WeId");

                    b.HasIndex("WpId");

                    b.ToTable("WorkoutExercises", (string)null);
                });

            modelBuilder.Entity("GymApp.Core.Entities.WorkoutPlan", b =>
                {
                    b.Property<int>("WpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WpId"));

                    b.Property<string>("ClCode")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<string>("CoCode")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("WpEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WpName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("WpStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WpId");

                    b.HasIndex("ClCode");

                    b.HasIndex("CoCode");

                    b.ToTable("WorkoutPlans", (string)null);
                });

            modelBuilder.Entity("GymApp.Core.Entities.Attendance", b =>
                {
                    b.HasOne("GymApp.Core.Entities.Client", "Client")
                        .WithMany("Attendances")
                        .HasForeignKey("ClCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GymApp.Core.Entities.Client", b =>
                {
                    b.HasOne("GymApp.Core.Entities.Coach", "Coach")
                        .WithMany("Clients")
                        .HasForeignKey("ClCoachId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GymApp.Core.Entities.MembershipPlan", "Membership")
                        .WithMany("Clients")
                        .HasForeignKey("ClMembershipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GymApp.Core.Entities.Dietitian", "Dietitian")
                        .WithMany("Clients")
                        .HasForeignKey("DietitianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GymApp.Core.Entities.User", "User")
                        .WithOne("Client")
                        .HasForeignKey("GymApp.Core.Entities.Client", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Dietitian");

                    b.Navigation("Membership");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymApp.Core.Entities.ClientGoal", b =>
                {
                    b.HasOne("GymApp.Core.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GymApp.Core.Entities.ClientMembership", b =>
                {
                    b.HasOne("GymApp.Core.Entities.Client", "Client")
                        .WithMany("ClientMemberships")
                        .HasForeignKey("ClCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymApp.Core.Entities.MembershipPlan", "MembershipPlan")
                        .WithMany("ClientMemberships")
                        .HasForeignKey("MemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("MembershipPlan");
                });

            modelBuilder.Entity("GymApp.Core.Entities.Coach", b =>
                {
                    b.HasOne("GymApp.Core.Entities.User", "User")
                        .WithOne("Coach")
                        .HasForeignKey("GymApp.Core.Entities.Coach", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymApp.Core.Entities.DietPlan", b =>
                {
                    b.HasOne("GymApp.Core.Entities.Client", "Client")
                        .WithMany("DietPlans")
                        .HasForeignKey("ClCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymApp.Core.Entities.Dietitian", "Dietitian")
                        .WithMany("DietPlans")
                        .HasForeignKey("DietitianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Dietitian");
                });

            modelBuilder.Entity("GymApp.Core.Entities.Dietitian", b =>
                {
                    b.HasOne("GymApp.Core.Entities.User", "User")
                        .WithOne("Dietitian")
                        .HasForeignKey("GymApp.Core.Entities.Dietitian", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymApp.Core.Entities.Notification", b =>
                {
                    b.HasOne("GymApp.Core.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymApp.Core.Entities.Payment", b =>
                {
                    b.HasOne("GymApp.Core.Entities.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymApp.Core.Entities.MembershipPlan", "MembershipPlan")
                        .WithMany("Payments")
                        .HasForeignKey("MemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("MembershipPlan");
                });

            modelBuilder.Entity("GymApp.Core.Entities.ProgressEntry", b =>
                {
                    b.HasOne("GymApp.Core.Entities.Client", "Client")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("ClientId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GymApp.Core.Entities.Review", b =>
                {
                    b.HasOne("GymApp.Core.Entities.Client", "Client")
                        .WithMany("Reviews")
                        .HasForeignKey("ClCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymApp.Core.Entities.Coach", "Coach")
                        .WithMany("Reviews")
                        .HasForeignKey("CoCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymApp.Core.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId");

                    b.Navigation("Client");

                    b.Navigation("Coach");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("GymApp.Core.Entities.Session", b =>
                {
                    b.HasOne("GymApp.Core.Entities.Client", "Client")
                        .WithMany("Sessions")
                        .HasForeignKey("SesClCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymApp.Core.Entities.Coach", "Coach")
                        .WithMany("Sessions")
                        .HasForeignKey("SesCoCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("GymApp.Core.Entities.WorkoutExercise", b =>
                {
                    b.HasOne("GymApp.Core.Entities.WorkoutPlan", "WorkoutPlan")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("GymApp.Core.Entities.WorkoutPlan", b =>
                {
                    b.HasOne("GymApp.Core.Entities.Client", "Client")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("ClCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymApp.Core.Entities.Coach", "Coach")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("CoCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("GymApp.Core.Entities.Client", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("ClientMemberships");

                    b.Navigation("DietPlans");

                    b.Navigation("Payments");

                    b.Navigation("ProgressEntries");

                    b.Navigation("Reviews");

                    b.Navigation("Sessions");

                    b.Navigation("WorkoutPlans");
                });

            modelBuilder.Entity("GymApp.Core.Entities.Coach", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Reviews");

                    b.Navigation("Sessions");

                    b.Navigation("WorkoutPlans");
                });

            modelBuilder.Entity("GymApp.Core.Entities.Dietitian", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("DietPlans");
                });

            modelBuilder.Entity("GymApp.Core.Entities.MembershipPlan", b =>
                {
                    b.Navigation("ClientMemberships");

                    b.Navigation("Clients");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("GymApp.Core.Entities.User", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("Coach");

                    b.Navigation("Dietitian");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("GymApp.Core.Entities.WorkoutPlan", b =>
                {
                    b.Navigation("WorkoutExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
