CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "MembershipPlans" (
    "MemId" integer GENERATED BY DEFAULT AS IDENTITY,
    "MemName" character varying(50) NOT NULL,
    "MemPrice" numeric(10,2) NOT NULL,
    "MemDurationDays" integer NOT NULL,
    "MemDescription" character varying(200),
    "MemStatus" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_MembershipPlans" PRIMARY KEY ("MemId")
);

CREATE TABLE "Users" (
    "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserEmail" character varying(50) NOT NULL,
    "UserPassword" character varying(255) NOT NULL,
    "UserRole" character varying(20) NOT NULL,
    "UserStatus" boolean NOT NULL,
    "CreatedDate" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
);

CREATE TABLE "Coaches" (
    "CoCode" character varying(5) NOT NULL,
    "UserId" integer NOT NULL,
    "CoFname" character varying(20) NOT NULL,
    "CoLname" character varying(20) NOT NULL,
    "CoBirthDate" timestamp without time zone NOT NULL,
    "CoPhone" character varying(15) NOT NULL,
    "CoEmail" character varying(50) NOT NULL,
    "CoAddress" character varying(100) NOT NULL,
    "CoHireDate" timestamp without time zone NOT NULL,
    "CoSpecialty" character varying(50),
    "CoStatus" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "Rating" numeric,
    CONSTRAINT "PK_Coaches" PRIMARY KEY ("CoCode"),
    CONSTRAINT "FK_Coaches_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE RESTRICT
);

CREATE TABLE "Dietitians" (
    "DietCode" character varying(5) NOT NULL,
    "UserId" integer NOT NULL,
    "DietFname" character varying(20) NOT NULL,
    "DietLname" character varying(20) NOT NULL,
    "DietEmail" character varying(50) NOT NULL,
    "DietPhone" character varying(15) NOT NULL,
    "DietStatus" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Dietitians" PRIMARY KEY ("DietCode"),
    CONSTRAINT "FK_Dietitians_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE RESTRICT
);

CREATE TABLE "Notifications" (
    "NotId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Title" text NOT NULL,
    "Message" character varying(200) NOT NULL,
    "Type" text,
    "CreatedDate" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "IsRead" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("NotId"),
    CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Clients" (
    "ClCode" character varying(5) NOT NULL,
    "UserId" integer NOT NULL,
    "ClFname" character varying(20) NOT NULL,
    "ClLname" character varying(20) NOT NULL,
    "ClBirthDate" timestamp without time zone NOT NULL,
    "ClPhone" character varying(15) NOT NULL,
    "ClAddress" character varying(100) NOT NULL,
    "ClRegisterDate" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ClStatus" boolean NOT NULL,
    "ClCoachId" character varying(5),
    "ClMembershipId" integer,
    "DietitianId" character varying(5),
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Clients" PRIMARY KEY ("ClCode"),
    CONSTRAINT "AK_Clients_UserId" UNIQUE ("UserId"),
    CONSTRAINT "FK_Clients_Coaches_ClCoachId" FOREIGN KEY ("ClCoachId") REFERENCES "Coaches" ("CoCode") ON DELETE RESTRICT,
    CONSTRAINT "FK_Clients_Dietitians_DietitianId" FOREIGN KEY ("DietitianId") REFERENCES "Dietitians" ("DietCode") ON DELETE RESTRICT,
    CONSTRAINT "FK_Clients_MembershipPlans_ClMembershipId" FOREIGN KEY ("ClMembershipId") REFERENCES "MembershipPlans" ("MemId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Clients_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE RESTRICT
);

CREATE TABLE "Attendances" (
    "AttId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClCode" character varying(5) NOT NULL,
    "CheckInTime" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "CheckOutTime" timestamp without time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Attendances" PRIMARY KEY ("AttId"),
    CONSTRAINT "FK_Attendances_Clients_ClCode" FOREIGN KEY ("ClCode") REFERENCES "Clients" ("ClCode") ON DELETE RESTRICT
);

CREATE TABLE "ClientGoals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClientCode" character varying(5) NOT NULL,
    "GoalType" text NOT NULL,
    "TargetValue" numeric NOT NULL,
    "CurrentValue" numeric,
    "StartDate" timestamp without time zone NOT NULL,
    "TargetDate" timestamp without time zone,
    "IsCompleted" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_ClientGoals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ClientGoals_Clients_ClientCode" FOREIGN KEY ("ClientCode") REFERENCES "Clients" ("ClCode") ON DELETE RESTRICT
);

CREATE TABLE "ClientMemberships" (
    "CmId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClCode" character varying(5) NOT NULL,
    "MemId" integer NOT NULL,
    "StartDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone NOT NULL,
    "Status" character varying(20) NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_ClientMemberships" PRIMARY KEY ("CmId"),
    CONSTRAINT "FK_ClientMemberships_Clients_ClCode" FOREIGN KEY ("ClCode") REFERENCES "Clients" ("ClCode") ON DELETE RESTRICT,
    CONSTRAINT "FK_ClientMemberships_MembershipPlans_MemId" FOREIGN KEY ("MemId") REFERENCES "MembershipPlans" ("MemId") ON DELETE RESTRICT
);

CREATE TABLE "DietPlans" (
    "DietId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClCode" character varying(5) NOT NULL,
    "DietitianId" character varying(5) NOT NULL,
    "DietStartDate" timestamp without time zone NOT NULL,
    "DietEndDate" timestamp without time zone NOT NULL,
    "DietDescription" character varying(200) NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_DietPlans" PRIMARY KEY ("DietId"),
    CONSTRAINT "FK_DietPlans_Clients_ClCode" FOREIGN KEY ("ClCode") REFERENCES "Clients" ("ClCode") ON DELETE RESTRICT,
    CONSTRAINT "FK_DietPlans_Dietitians_DietitianId" FOREIGN KEY ("DietitianId") REFERENCES "Dietitians" ("DietCode") ON DELETE RESTRICT
);

CREATE TABLE "Payments" (
    "PayId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClCode" character varying(5) NOT NULL,
    "MemId" integer NOT NULL,
    "PayAmount" numeric(10,2) NOT NULL,
    "PayMethod" character varying(20) NOT NULL,
    "PayDate" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "PayStatus" character varying(20) NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("PayId"),
    CONSTRAINT "FK_Payments_Clients_ClCode" FOREIGN KEY ("ClCode") REFERENCES "Clients" ("ClCode") ON DELETE RESTRICT,
    CONSTRAINT "FK_Payments_MembershipPlans_MemId" FOREIGN KEY ("MemId") REFERENCES "MembershipPlans" ("MemId") ON DELETE RESTRICT
);

CREATE TABLE "ProgressEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClientId" integer NOT NULL,
    "Weight" numeric,
    "BodyFatPercentage" numeric,
    "Chest" numeric,
    "Waist" numeric,
    "Notes" text,
    "EntryDate" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_ProgressEntries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProgressEntries_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("UserId") ON DELETE RESTRICT
);

CREATE TABLE "Sessions" (
    "SesId" integer GENERATED BY DEFAULT AS IDENTITY,
    "SesClCode" character varying(5) NOT NULL,
    "SesCoCode" character varying(5) NOT NULL,
    "SesType" character varying(20) NOT NULL,
    "SesDescription" character varying(100),
    "SesDateTime" timestamp without time zone NOT NULL,
    "SesDuration" integer NOT NULL,
    "SesStatus" character varying(20) NOT NULL DEFAULT 'Scheduled',
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Sessions" PRIMARY KEY ("SesId"),
    CONSTRAINT "FK_Sessions_Clients_SesClCode" FOREIGN KEY ("SesClCode") REFERENCES "Clients" ("ClCode") ON DELETE RESTRICT,
    CONSTRAINT "FK_Sessions_Coaches_SesCoCode" FOREIGN KEY ("SesCoCode") REFERENCES "Coaches" ("CoCode") ON DELETE RESTRICT
);

CREATE TABLE "WorkoutPlans" (
    "WpId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClCode" character varying(5) NOT NULL,
    "CoCode" character varying(5) NOT NULL,
    "WpName" character varying(50) NOT NULL,
    "WpStartDate" timestamp without time zone NOT NULL,
    "WpEndDate" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_WorkoutPlans" PRIMARY KEY ("WpId"),
    CONSTRAINT "FK_WorkoutPlans_Clients_ClCode" FOREIGN KEY ("ClCode") REFERENCES "Clients" ("ClCode") ON DELETE RESTRICT,
    CONSTRAINT "FK_WorkoutPlans_Coaches_CoCode" FOREIGN KEY ("CoCode") REFERENCES "Coaches" ("CoCode") ON DELETE RESTRICT
);

CREATE TABLE "Reviews" (
    "RevId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClCode" character varying(5) NOT NULL,
    "CoCode" character varying(5) NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" character varying(200),
    "CreatedDate" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "IsDeleted" boolean NOT NULL,
    "SessionId" integer,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("RevId"),
    CONSTRAINT "FK_Reviews_Clients_ClCode" FOREIGN KEY ("ClCode") REFERENCES "Clients" ("ClCode") ON DELETE RESTRICT,
    CONSTRAINT "FK_Reviews_Coaches_CoCode" FOREIGN KEY ("CoCode") REFERENCES "Coaches" ("CoCode") ON DELETE RESTRICT,
    CONSTRAINT "FK_Reviews_Sessions_SessionId" FOREIGN KEY ("SessionId") REFERENCES "Sessions" ("SesId")
);

CREATE TABLE "WorkoutExercises" (
    "WeId" integer GENERATED BY DEFAULT AS IDENTITY,
    "WpId" integer NOT NULL,
    "ExerciseName" character varying(50) NOT NULL,
    "Sets" integer NOT NULL,
    "Reps" integer NOT NULL,
    "RestSeconds" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_WorkoutExercises" PRIMARY KEY ("WeId"),
    CONSTRAINT "FK_WorkoutExercises_WorkoutPlans_WpId" FOREIGN KEY ("WpId") REFERENCES "WorkoutPlans" ("WpId") ON DELETE CASCADE
);

CREATE INDEX "IX_Attendances_ClCode" ON "Attendances" ("ClCode");

CREATE INDEX "IX_ClientGoals_ClientCode" ON "ClientGoals" ("ClientCode");

CREATE INDEX "IX_ClientMemberships_ClCode" ON "ClientMemberships" ("ClCode");

CREATE INDEX "IX_ClientMemberships_MemId" ON "ClientMemberships" ("MemId");

CREATE INDEX "IX_Clients_ClCoachId" ON "Clients" ("ClCoachId");

CREATE INDEX "IX_Clients_ClMembershipId" ON "Clients" ("ClMembershipId");

CREATE INDEX "IX_Clients_DietitianId" ON "Clients" ("DietitianId");

CREATE UNIQUE INDEX "IX_Coaches_UserId" ON "Coaches" ("UserId");

CREATE UNIQUE INDEX "IX_Dietitians_UserId" ON "Dietitians" ("UserId");

CREATE INDEX "IX_DietPlans_ClCode" ON "DietPlans" ("ClCode");

CREATE INDEX "IX_DietPlans_DietitianId" ON "DietPlans" ("DietitianId");

CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");

CREATE INDEX "IX_Payments_ClCode" ON "Payments" ("ClCode");

CREATE INDEX "IX_Payments_MemId" ON "Payments" ("MemId");

CREATE INDEX "IX_ProgressEntries_ClientId" ON "ProgressEntries" ("ClientId");

CREATE INDEX "IX_Reviews_ClCode" ON "Reviews" ("ClCode");

CREATE INDEX "IX_Reviews_CoCode" ON "Reviews" ("CoCode");

CREATE INDEX "IX_Reviews_SessionId" ON "Reviews" ("SessionId");

CREATE INDEX "IX_Sessions_SesClCode" ON "Sessions" ("SesClCode");

CREATE INDEX "IX_Sessions_SesCoCode" ON "Sessions" ("SesCoCode");

CREATE UNIQUE INDEX "IX_Users_UserEmail" ON "Users" ("UserEmail");

CREATE INDEX "IX_WorkoutExercises_WpId" ON "WorkoutExercises" ("WpId");

CREATE INDEX "IX_WorkoutPlans_ClCode" ON "WorkoutPlans" ("ClCode");

CREATE INDEX "IX_WorkoutPlans_CoCode" ON "WorkoutPlans" ("CoCode");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260410144809_InitialCreate', '10.0.5');

COMMIT;

